#! /bin/bash

# Copyright (C) 2022-2024, Pavel Raiskup

# Even though everything should be ready in many cases, use Gemfile and install
# the dependencies now (if any are missing).

bundler_log=/tmp/bundler-install.log
echo "Installing deps, may take several minutes (see $bundler_log in container)"
bundler install &> "$bundler_log"

# We start Jekyll on the port 5000, even though we expose port 4000 in
# Dockerfile (the normal default port of local Jekyll).  The problem is that
# Jekyll doesn't seem to accept connections elsewhere than on 127.0.0.1, which
# is not the case when Podman container is accessed from host:
# https://github.com/jekyll/jekyll/issues/8846

jekyll_log=/tmp/jekyll-server.log
bundler exec jekyll serve --drafts --port 5000 --incremental &>"$jekyll_log" &

# Execute tinyproxy, which allows connections from 0.0.0.0, and redirects the
# container's 4000 port to Jekyll's 5000.

cat <<EOF
=========================================
 Server listens on http://127.0.0.1:4000
 Jekyll Log: $jekyll_log (in container)
 Install logs: $bundler_log (in container)
=========================================
EOF
tinyproxy -d
